name: CD - Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Проверка кода
    - name: Checkout code
      uses: actions/checkout@v3

    # Логин в Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Построение и отправка Docker-образа
    - name: Build and push Docker image
      run: |
        docker build -t mydockerhubusername/my-python-app:latest .
        docker push mydockerhubusername/my-python-app:latest
