name: CI - Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Проверка кода
    - name: Checkout code
      uses: actions/checkout@v3

    # Установка Docker
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    # Построение Docker-образа для тестирования
    - name: Build Docker image
      run: docker build -t my-python-app .

    # Запуск тестов
    - name: Run tests
      run: docker run my-python-app python -m unittest discover -s tests
